import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const NanumSquareNeo = localFont({
  src: "./fonts/NanumSquareNeo-Variable.ttf",
  weight: "100 900",
  variable: "--font-nanumsquareneo",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko"className={`${NanumSquareNeo.variable} antialiased`}>
      <body
        className="font-nanumsquareneo"
      >
        {children}
      </body>
    </html>
  );
}
